# -*- coding: utf-8 -*-
"""chat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMZR8dM2stbK5SMn87wswpBrN2NnbHgJ
"""

# Install Streamlit and pyngrok for running the app
!pip install streamlit pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# # Create the chatbot.py file
# %%writefile chatbot.py
# import streamlit as st
# 
# def run_chatbot():
#     st.title("A. Rule-Based AI Chatbot")
#     st.markdown("This is a simple chatbot using keyword matching. Try: greetings, course info, timetable, fees, goodbye.")
# 
#     if "chat_history" not in st.session_state:
#         st.session_state.chat_history = []
# 
#     for message in st.session_state.chat_history:
#         with st.chat_message(message["role"]):
#             st.markdown(message["content"])
# 
#     user_input = st.chat_input("Type your message...")
# 
#     if user_input:
#         st.session_state.chat_history.append({"role": "user", "content": user_input})
#         with st.chat_message("user"):
#             st.markdown(user_input)
# 
#         response = get_response(user_input.lower())
#         st.session_state.chat_history.append({"role": "assistant", "content": response})
#         with st.chat_message("assistant"):
#             st.markdown(response)
# 
# def get_response(text):
#     if any(word in text for word in ["hello", "hi", "greetings"]):
#         return "Hello! How can I help you?"
#     elif any(word in text for word in ["course", "info", "classes"]):
#         return "We offer Python, Data Science, and AI courses."
#     elif any(word in text for word in ["timetable", "schedule"]):
#         return "Classes: Mon-Fri, 9 AM - 5 PM."
#     elif any(word in text for word in ["fees", "cost"]):
#         return "Fees start at $500. Scholarships available."
#     elif any(word in text for word in ["bye", "goodbye"]):
#         return "Goodbye! Have a great day."
#     else:
#         return "Sorry, I didn't understand. Please rephrase."
# 
# # Create app.py to run it
# %%writefile app.py
# import streamlit as st
# from chatbot import run_chatbot
# 
# st.set_page_config(page_title="Chatbot", layout="wide")
# run_chatbot()

from pyngrok import ngrok

ngrok.set_auth_token("ngrok config add-authtoken 2l7KUNDK41QW3MhhWS8rjXd62y5_84CBzDi5rzyfPiPSBuzes")

